#!/usr/bin/env python
# coding: utf-8

# A string is simply an ordered collection of symbols selected from some alphabet and formed into a word; the length of a string is the number of symbols that it contains.
# 
# An example of a length 21 DNA string (whose alphabet contains the symbols 'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."
# 
# Given: A DNA string s of length at most 1000 nt.
# 
# Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.

# This seems simple enough.

# In[7]:


def nucleotide_counter(data):
    A = 0  
    C = 0
    G = 0
    T = 0
    for s in data:
        if s == 'A':
            A += 1 
        elif s == 'C':
            C += 1
        elif s == 'G':
            G += 1    
        elif s == 'T':
            T += 1
    return [A, C, G, T]

test = 'AGCAGGCTGTAGGGAAAATGTAGTTATGTTAGTAAGGGGAAGGTTCTTTTCTGAGCTACCTTGCTTGGCACCGAGTGCGGACGACAATCTCAGAAATCTTCGCCTGGCCGGAGTACCCCGGTTACGCTGGCCTCGTCTTCGCCTTTCGAAATCATGGGAACTACATACTGGGACGGAGCTAAGTTTGCGGAGACCAACCCCTGTCGCCACGCTGTGTTTAATCACGTCATCAAACGGCCTAGTAGGAGCTTAGTGCTCGCCGGGTAACTTGAAAGGCTACCTGACGAAGGCATAATCATCTCCGGCCTTTCGACTAATGAACGGTACACGGCCATTTATTCGACGAGTTCGATCTTACGTGGTCCAAGTCTCCTTCGCTGTACTGCGTAATGAATGAACTTAACTATAGATTTGCATCAATAAATCCGGGCCTAGGGTAGTGAATTACTTAAAGAGGGGGATATCGTTCATTATACAGGAAGTTTCTCATCGACATGTCATACTCTCGAGTTGTGCCCCGCACTATAGCCATACCTGCGATCGCTGTTTAATAGTTGCAGGGTGGGCCTACCTACTCAATTCACGTTACGGATAACGATCATGCTCCCGGCTAATGATCGTCCGCGGACGTCTCTCTTTCACGTCACTTTAGCCCGTTCTTAGTTGATGCTCGCGCGCACTCTTGAATAGTTACCGACGCTCTCGCGGTTGACGATCCCAGTTACCTACCCTCCGCACTGCCTGTATAGTGACCAAACATGCGTAACGCTGATCATCTTCACGTGAATGGACACTTCATCGTTTGTATCTTCATCCTAATCGAACGATACTTCGTGGCAAGGCCTTTCCGAGTCATGGGCTGCGTAACGCTTCATAAAGATATTCCTACTGATCTCTACGAGCAGCAGGGTTATGACGATTAGGAGGCTCATCCAGAATGCACCATCGATGTGCTGGACGACAT'
print('The number of nucleotides is: ')
print(nucleotide_counter(test))


# In[ ]:




